### ISSUE TITLE
any warkaround of using google service ?

### ISSUE THREAD

**Issue by khalilxg** [ammirsm/llamaindex-omakase-rag#7]

**Comment by ammirsm** [comment]
Hey, can you provide more context please?

**Comment by khalilxg** [comment]
The app is restricted on using google service,is there a way to not use it goal is not attaching the app to any provider

**Comment by ammirsm** [comment]
@khalilxg what kind of provider you would like to use? You mean instead of having google drive using other type of connectors from LlamaIndex?

**Comment by khalilxg** [comment]
Thanks, i've figure out google drive is top easy to use choice !
